### PR TITLE
ID NS LMFAO LOL JK GTFO GG RIP SNAFU

### LINKED ISSUE #124: Namespace Declarations
Currently, this is how we can access a name in our namespace:

`postfix_expr DOT ID { Access($1, $3) }`

However, this will lead to only variables declared within namespaces to actually be accessible. Hence, the following code doesn't parse:

```
ns foo = {
   kn bar() int { 
      0
   }
}

kn main() int {
    foo.bar()
}
```

`foo.bar()` cannot be parsed under the given rule since `bar()` call is never an `ID`.

### PR DESCRIPTION
**Pull request by j-hui**
fixes #124

### CODE REVIEW

**Comment by j-hui** [comment]
@Contentmaudlin this breaks `semant.ml`, so you'll need to change that..

**Comment by j-hui** [comment]
WAIT DO NOT MERGE THERE IS SR CONFLICT

**Comment by lucas-schuermann** [comment]
dat title

**Comment by Contentmaudlin** [comment]
Help my language is dying

**Comment by j-hui** [comment]
>pick an operator, any operator

When designing the syntax of our language, we wanted to design it to be expressive yet readable from the **ground up**. We don't want to just write programs with our language, we want to _tell stories_. We thought about how to best depict that story, and built our grammar around that syntax.

**Review by Contentmaudlin — COMMENTED** [review]
This has faults. I fixed them. New PR coming.

**Pull request closed without merging**
