### PR TITLE
Remove unused stuff

### PR DESCRIPTION
**Pull request by andylhxu**
Removed unused functions and type decl in codegen.ml.
Removed unused `install_dep.sh` script in favor of new script to be built.

### CODE REVIEW

**Comment by andylhxu** [comment]
Once this PR is reviewed and merged, we can create a new demo branch out of master.

**Comment by lucas-schuermann** [comment]
Yo wait why did you remove the install dependencies script? That was so that people could easily build the language on their own.

**Comment by lucas-schuermann** [comment]
I think we can just modify it to install LLVM3.6 properly. New script should be internal to us, perhaps? Again, this would be for possible external contributors

**Comment by andylhxu** [comment]
@j-hui is building a new script now supporting the latest llvm version based on the os/kernel version. The script is deprecated and should not be there in our repo, at least for now. We are using the vm anyways.

**Review by lucas-schuermann — APPROVED** [review]
Reluctantly saying bye to our .sh baby

**Pull request merged**
